apiVersion: apps/v1
kind: Deployment
metadata:
  name: springkube-app
  namespace: springkube
spec:
  replicas: 2
  strategy:
    type: RollingUpdate
    rollingUpdate:
      maxSurge: 1 # 한번에 하나씩 업데이트
      maxUnavailable: 0
  selector:
    matchLabels:
      app: springkube-app
  template:
    metadata:
      labels:
        app: springkube-app
    spec:
      terminationGracePeriodSeconds: 60 # 30이 기본 값
      containers:
        - name: springkube
          image: kai1114/springkube:0.0.6
          imagePullPolicy: Always
          resources:
            requests:
              memory: "512Mi"
              cpu: "1000m" # 1코어
            limits:
              memory: "1Gi"
              cpu: "1500m" # 1.5코어
          lifecycle:
            preStop:
              exec:
                command: [ "sh", "-c", "sleep 10" ] # 10초 후, SIGTERM 전달
          startupProbe:
            httpGet:
              path: /probe/startup
              port: 8080
            initialDelaySeconds: 45
            periodSeconds: 1
            failureThreshold: 10
          readinessProbe:
            httpGet:
              path: /probe/ready
              port: 8080
            initialDelaySeconds: 45 # startup와 무관하게 컨테이너 실행 시점부터 20초 후부터 체크
            periodSeconds: 1
            successThreshold: 2
            failureThreshold: 3
          livenessProbe:
            httpGet:
              path: /probe/live
              port: 8080
            initialDelaySeconds: 45
            periodSeconds: 1
            failureThreshold: 3
