apiVersion: v1
kind: ConfigMap
metadata:
  name: fluentbit-config
  namespace: springkube
data:
  fluent-bit.conf: |
    [SERVICE]
        Flush        1
        Log_Level    info
    
    [INPUT]
        Name         tail
        Path         /var/log/app/app-hello.log
    
    [OUTPUT]
        Name         opensearch
        Match        *
        Host         opensearch-cluster-master.opensearch.svc.cluster.local
        Port         9200
        Logstash_Format On
        Logstash_Prefix app-hello-logs
        Suppress_Type_Name On
        tls          On
        tls.verify   Off
        http_User    admin
        http_Passwd  World56!@87