spring:
  application:
    name: springkube-batch
  data:
    redis:
      host: redis-service.default.svc.cluster.local
      port: 6379
  datasource:
    driver-class-name: org.h2.Driver
    url: jdbc:h2:mem:testdb
    username: sa
    password:
server:
  shutdown: graceful
